# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-11 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSubmitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerSubmitted', models.CharField(max_length=51)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAnswer', models.CharField(max_length=51)),
            ],
        ),
        migrations.CreateModel(
            name='Qcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Qoptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options1', models.CharField(max_length=51)),
                ('options2', models.CharField(max_length=51)),
                ('options3', models.CharField(max_length=51)),
                ('options4', models.CharField(max_length=51)),
            ],
        ),
    ]
